server:
  port: 80

logging:
  level: info

spring:
  datasource:
    url: jdbc:mysql://localhost/wexin?useUnicode=true&characterEncoding=utf-8
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver

